import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Script from 'next/script'
const inter = Inter({ subsets: ['latin'] })
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import QueryProvider from '@/components/QueryProvider'
import Nav from '@/components/navigation/nav'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <QueryProvider>

        <Nav/>
       
        
        {children}

        <Toaster
         position='top-center'
         richColors={true}
         closeButton={true}
        />
        </QueryProvider>
        </body>
    </html>
  )
}
